name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm-community'
        java-version: '20'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: "run tests"
      run: mvn -PnativeTest test